name: Dockerfile linter
on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  linter:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian
    steps:
      - uses: actions/checkout@v3
      - run: ls python_on_docker/
      - run: hadolint python_on_docker/
